### ISSUE TITLE
Correct "dijet" to "QCD"

### ISSUE THREAD

**Issue by okarkout** [umami-hep/puma#167]
https://github.com/umami-hep/puma/blob/5a345a4ec5e9c8039fccec23646affc544ae6e82/puma/utils/__init__.py#L292

This line should say "QCD" instead of "dijets"
It describes a large-R jet which comes from light qcd processes.

**Comment by samvanstroud** [comment]
Thanks @okarkout, this should indeed be changed, but not that we deprecate the `flavour_categories` info here in favour of using `Flavour` objects from the new [atlas-ftag-tools](https://github.com/umami-hep/atlas-ftag-tools/) package. (Where we indeed use [`qcd`](https://github.com/umami-hep/atlas-ftag-tools/blob/main/ftag/flavours.yaml#L66) instead of `dijets`)

**Comment by okarkout** [comment]
I plan a merge request to Umami providing example configs for xbb preprocessing. I'll use QCD as a flavour category in them, contingent on editing this line in puma.

**Comment by dkobylianskii** [comment]
Hi Osama,
The `dijets` was replaced with `QCD`.
